name: Build package distribution

on:
  workflow_call:
    inputs:
      ref:
        description: |-
          The branch, tag or SHA to checkout.
        type: string
        required: true

env:
  CI_POETRY_VERSION: "1.6.1"

jobs:
  build-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source tree
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Load cached Poetry installation
        id: load-cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-release-v${{ env.CI_POETRY_VERSION }}

      - name: Update PATH
        if: steps.load-cached-poetry.outputs.cache-hit == 'true'
        run: |
          echo ~/.local/bin >> "${GITHUB_PATH}"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: steps.load-cached-poetry.outputs.cache-hit != 'true'
        with:
          version: ${{ env.CI_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Print current package version
        run: poetry version --no-ansi --no-interaction

      - name: Use specified Python version
        uses: actions/setup-python@v5
        with:
          cache: poetry
          python-version-file: .python-version

      - name: Build wheel and source tarball
        run: poetry build --no-ansi --no-interaction

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error
