name: Run CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out source tree
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Use specified Python version
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: Install dependencies
        # See also:
        # https://github.com/python-poetry/poetry/issues/7184
        run: poetry install --no-ansi --no-interaction --no-root

      - name: Install target package
        run: poetry install --no-ansi --no-interaction

      - name: Run static typechecking
        run: poetry run poe typecheck

      - name: Run linter
        run: poetry run poe linter

      - name: Run unit tests
        run: poetry run poe tests
