name: Manually test draft release creation

on:
  - workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/release_feed_mediola
    permissions:
      id-token: write
    steps:
      # Checking out just to make `gh release create` work.
      # Using `gh release create --repo` on its own would yield
      # an `HTTP 403: Resource not accessible by integration` error.
      - name: Check out source tree
        uses: actions/checkout@v3

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -ex
          VERSION="v0.123.4.5.6-test"
          gh release create "v${VERSION}" \
            --draft --generate-notes \
            --target 4c9d087ca4480bb5a862a49d88ce15e79bf20963
