name: Manually test draft release creation

on:
  - workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/release_feed_mediola
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          set -ex
          VERSION="0.123.4.5.6-test"
          echo Bar > foo
          gh release create "v${VERSION}" \
            --draft --generate-notes \
            --repo "${REPOSITORY}" --target 4c9d087ca4480bb5a862a49d88ce15e79bf20963
          gh release upload "v${VERSION}" foo \
            --repo "${REPOSITORY}"
