name: Create a release

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: |-
          New version number for the release (or a Poetry bump rule)
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source tree
        uses: actions/checkout@v3

      - name: Load cached Poetry installation
        id: load-cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-release-v${{ env.CI_POETRY_VERSION }}

      - name: Update PATH
        if: steps.load-cached-poetry.outputs.cache-hit == 'true'
        run: |
          echo ~/.local/bin >> "${GITHUB_PATH}"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: steps.load-cached-poetry.outputs.cache-hit != 'true'
        with:
          version: ${{ env.CI_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Print current package version
        run: poetry version --no-ansi --no-interaction

      - name: Bump package version
        env:
          TARGET_VERSION: ${{ inputs.target_version }}
        run: poetry version --no-ansi --no-interaction "${TARGET_VERSION}"

      - name: Gather bumped package version
        run: |
          env -i >> "${GITHUB_ENV}" \
            "NEW_VERSION=$(poetry version --no-ansi --no-interaction --short)"

      - name: Print bumped package version
        run: |
          echo "New package version: ${NEW_VERSION}"

      - name: Commit bumped package version
        uses: EndBug/add-and-commit@v9
        with:
          add: pyproject.toml
          message: Bump version to ${{ env.NEW_VERSION }}
          new_branch: version-bump/${{ env.NEW_VERSION }}
          pathspec_error_handling: exitImmediately
          push: |-
            origin version-bump/${{ env.NEW_VERSION }} --force

  ci-checks:
    needs: bump-version
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci-checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source tree
        uses: actions/checkout@v3
