name: Create a release

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: |-
          New version number for the release (or a Poetry bump rule)
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source tree
        uses: actions/checkout@v3

      - name: Load cached Poetry installation
        id: load-cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-release-v${{ env.CI_POETRY_VERSION }}

      - name: Update PATH
        if: steps.load-cached-poetry.outputs.cache-hit == 'true'
        run: |
          echo ~/.local/bin >> "${GITHUB_PATH}"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: steps.load-cached-poetry.outputs.cache-hit != 'true'
        with:
          version: ${{ env.CI_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Print current package version
        run: poetry version --no-ansi --no-interaction

      - name: Bump package version
        env:
          TARGET_VERSION: ${{ inputs.target_version }}
        run: poetry version --no-ansi --no-interaction "${TARGET_VERSION}"

      - name: Gather bumped package version
        run: |
          env -i >> "${GITHUB_ENV}" \
            "NEW_VERSION=$(poetry version --no-ansi --no-interaction --short)"

      - name: Print bumped package version
        run: |
          echo "New package version: ${NEW_VERSION}"

      # Workaround for https://github.com/actions/runner/issues/667
      # See also:
      # https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c
      - name: Commit bumped package version
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: pyproject.toml
          RELEASE_BRANCH: release/${{ env.NEW_VERSION }}
        run: |
          set -ex
          MESSAGE="Bump version to ${NEW_VERSION}"
          BASE_REF_SHA="$(git rev-parse @)"
          OBJECT_SHA=$(git rev-parse ":${FILE_TO_COMMIT}")
          gh api --method POST '/repos/:owner/:repo/git/refs' \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            --field ref="refs/heads/${RELEASE_BRANCH}" \
            --field sha="${BASE_REF_SHA}"
          gh api --method PUT "/repos/:owner/:repo/contents/${FILE_TO_COMMIT}" \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            --field message="${MESSAGE}" \
            --field content=@<(base64 -i "${FILE_TO_COMMIT}") \
            --field branch="${RELEASE_BRANCH}" \
            --field sha="${OBJECT_SHA}"
          gh api --method POST '/repos/:owner/:repo/pulls' \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            --field title="${MESSAGE}" \
            --field head="${RELEASE_BRANCH}" \
            --field base="${DEFAULT_BRANCH}" \
            --field body='When this PR is merged, a workflow will'`
              `' automatically create a tag and publish a release.' \
            > "${HOME}/create_pr_response.json"
          env -i >> "${GITHUB_ENV}" \
            "PR_ID=$(jq -r '.id' "${HOME}/create_pr_response.json")"

      - name: Add label to pull request
        run: |
          set -ex
          gh api --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            "/repos/:owner/:repo/labels" \
            --field name='auto-release' \
            --field description='Will create tag and release on merge' \
            --field color='7f0000' \
            || true
          gh api --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            "/repos/:owner/:repo/pulls/${PR_ID}/labels" \
            --field 'labels[]=auto-release'

  ci-checks:
    needs: bump-version
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci-checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source tree
        uses: actions/checkout@v3
